title: "Моё Портфолио"
description: "Веб-портфолио Филоненко Н.М."
baseurl: "" 
url: "https://JunHerz.github.io" 
theme: jekyll-theme-cayman
# Дополнительные настройки для темы Cayman
dinky_theme:
  skin: dark
  accent_color: "#d9d2e9"
# header_image: "assets/images/LogoPortfolio.jpg"
