title: "Моё Портфолио"
description: "Веб-портфолио Филоненко Н.М."
baseurl: ""
url: "https://JunHerz.github.io"

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

# Настройки темы Dinky 
hacker_theme:
  skin: dark
  accent_color: "#d9d2e9" # Фиолетовый оттенок
