remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Моё Портфолио"
description: "Веб-портфолио Филоненко Н.М."
baseurl: "" 
url: "https://JunHerz.github.io" 
theme: jekyll-theme-cayman
# Дополнительные настройки для темы Cayman
dinky_theme:
  skin: dark
  accent_color: "#d9d2e9"
# header_image: "assets/images/LogoPortfolio.jpg"
